name: Myriad Gen

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  myriad-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://${{ secrets.USERNAME }}:${{ secrets.TOKEN }}@github.com/lewagon/python-utilities.git
          pip install git+https://${{ secrets.USERNAME }}:${{ secrets.TOKEN }}@github.com/lewagon/challengify.git
          pip install git+https://${{ secrets.USERNAME }}:${{ secrets.TOKEN }}@github.com/lewagon/myriad.git
      - name: Generate myriads
        run: |
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            MYRIAD_BASE_REF="$GITHUB_BASE_REF"
          else
            MYRIAD_BASE_REF="${{ github.ref_name }}"
          fi
          myriad gen \
            --gha \
            --event "$GITHUB_EVENT_NAME" \
            --organization "$GITHUB_REPOSITORY_OWNER" \
            --course "$GITHUB_REPOSITORY" \
            --head-ref "$GITHUB_HEAD_REF" \
            --base-ref "$MYRIAD_BASE_REF" \
            --gh-nickname "${{ secrets.USERNAME }}" \
            --gh-token "${{ secrets.TOKEN }}"
