name: Myriad Unicity

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  myriad-unicity:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -U pip
        pip install git+https://github.com/lewagon/python-utilities
        pip install git+https://github.com/lewagon/challengify
        pip install git+https://github.com/lewagon/myriad

    - name: Sanity check for myriad unicity
      run: |
        myriad unicity \
          --gha \
          --course "$GITHUB_REPOSITORY"
