name: "Run Test"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Add pipconf
        run: |
          mkdir ~/.pip
          cat << EOF >> ~/.pip/pip.conf
          [global]
          trusted-host = pypi.fury.io
          extra-index-url = https://${{ secrets.GEMFURY_PULL_TOKEN }}@pypi.fury.io/ssaunier
          EOF

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install git+https://gmanchon:${{ secrets.TOKEN }}@github.com/lewagon/python-utilities.git@git-repos
          pip install -e .

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Install package and test
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.AUTOBOT_QA_ADMIN_TOKEN }}
        run: |
          make pytest
